// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository_sqlc

import (
	"database/sql"
)

type UsrAuth struct {
	ID        int64          `json:"id"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	Status    bool           `json:"status"`
	ProfileID int64          `json:"profile_id"`
	Token     sql.NullString `json:"token"`
	Password  sql.NullString `json:"password"`
}

type UsrProfile struct {
	ID          int64        `json:"id"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	Name        string       `json:"name"`
	Permissions []string     `json:"permissions"`
}

type UsrUser struct {
	ID        int64          `json:"id"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	Name      sql.NullString `json:"name"`
	Username  sql.NullString `json:"username"`
	Mail      sql.NullString `json:"mail"`
	AuthID    sql.NullInt64  `json:"auth_id"`
}
