// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository_sqlc

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO usr_profile (
  created_at, updated_at, name, permissions
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, created_at, updated_at, name, permissions
`

type CreateProfileParams struct {
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	Name        string       `json:"name"`
	Permissions []string     `json:"permissions"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (UsrProfile, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		pq.Array(arg.Permissions),
	)
	var i UsrProfile
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		pq.Array(&i.Permissions),
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO usr_user (
  created_at, updated_at, name, username, mail, auth_id
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, created_at, updated_at, name, username, mail, auth_id
`

type CreateUserParams struct {
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	Name      sql.NullString `json:"name"`
	Username  sql.NullString `json:"username"`
	Mail      sql.NullString `json:"mail"`
	AuthID    sql.NullInt64  `json:"auth_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (UsrUser, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Username,
		arg.Mail,
		arg.AuthID,
	)
	var i UsrUser
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Username,
		&i.Mail,
		&i.AuthID,
	)
	return i, err
}

const createUsersBatch = `-- name: CreateUsersBatch :many
INSERT INTO usr_user (name, username, mail)
SELECT unnest($1::text[]), unnest($2::text[]), unnest($3::text[])
RETURNING id, created_at, updated_at, name, username, mail, auth_id
`

type CreateUsersBatchParams struct {
	Column1 []string `json:"column_1"`
	Column2 []string `json:"column_2"`
	Column3 []string `json:"column_3"`
}

func (q *Queries) CreateUsersBatch(ctx context.Context, arg CreateUsersBatchParams) ([]UsrUser, error) {
	rows, err := q.db.QueryContext(ctx, createUsersBatch, pq.Array(arg.Column1), pq.Array(arg.Column2), pq.Array(arg.Column3))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsrUser
	for rows.Next() {
		var i UsrUser
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Username,
			&i.Mail,
			&i.AuthID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfile = `-- name: GetProfile :one
SELECT id, created_at, updated_at, name, permissions FROM usr_profile
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProfile(ctx context.Context, id int64) (UsrProfile, error) {
	row := q.db.QueryRowContext(ctx, getProfile, id)
	var i UsrProfile
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		pq.Array(&i.Permissions),
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, updated_at, name, username, mail, auth_id FROM usr_user
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (UsrUser, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i UsrUser
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Username,
		&i.Mail,
		&i.AuthID,
	)
	return i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, created_at, updated_at, name, permissions FROM usr_profile
ORDER BY id
`

func (q *Queries) ListProfiles(ctx context.Context) ([]UsrProfile, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsrProfile
	for rows.Next() {
		var i UsrProfile
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			pq.Array(&i.Permissions),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
