// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository_sqlc

import (
	"context"
)

type Querier interface {
	CreateProfile(ctx context.Context, arg CreateProfileParams) (UsrProfile, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (UsrUser, error)
	CreateUsersBatch(ctx context.Context, arg CreateUsersBatchParams) ([]UsrUser, error)
	GetProfile(ctx context.Context, id int64) (UsrProfile, error)
	GetUser(ctx context.Context, id int64) (UsrUser, error)
	ListProfiles(ctx context.Context) ([]UsrProfile, error)
}

var _ Querier = (*Queries)(nil)
